Overview.html
Overview.src.html

PR associated with Issue #32.
I also clarified that the "silent" flag encapsulates vibrations as well as sounds. In our implementation it also blocks system-default light indications, but since the notification doesn't supports lights (yet) I don't think we have to add that now.

Add renotify, silent, noscreen and sticky as attributes.

---

notifications.bs
notifications.html

Fixes #20.
The `timestamp` of a notification is the time, in milliseconds since
the epoch, of the event for which the notification was created. Web
developers can use this if the time of this event does not match the
time at which the notification is being shown, which can be the case
when notifying the user of upcoming calendar events.
Note that the `Boilerplate` change in the meta-data is Tab's
suggestion in https://github.com/tabatkins/bikeshed/issues/470.

Add Notification.timestamp and NotificationOptions.timestamp

---

notifications.bs

This PR adds a `notificationclose` event to the service worker API, fired for persistent notifications closed by the user. This should satisfy #31 and marco-c/wp-web-push#63.
Right now, the *action* attribute would be set to null. As an alternative, we might want to split the `Notification` object into two different objects: `NotificationClick` and `NotificationClose`.

Add notificationclose event

---

notifications.bs
notifications.html

There's a link as an HTML comment, but feels like it should be visible when reading the spec.

Add note about intent of fetching

---

notifications.bs

Fixes #95
***
[Preview](https://s3.amazonaws.com/pr-preview/beverloo/notifications/wording-fix.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/notifications/8eaabd2...beverloo:1779473.html)

Improve wording of the upfront-permission-request warning

---

notifications.bs

As defined by and discussed in https://github.com/whatwg/html/pull/2518.
***
[Preview](https://notifications.spec.whatwg.org/branch-snapshots/annevk/serialize-for-storage/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/notifications/fb423c7...d2db32f.html)

Use StructuredSerializeForStorage

---

LICENSE
notifications.bs

Do not merge until https://github.com/tabatkins/bikeshed/pull/1155 is merged.
***
<a href="https://whatpr.org/notifications/118.html" title="Last updated on Jan 4, 2018, 12:02 AM GMT (2134d54)">Preview</a> | <a href="https://whatpr.org/notifications/118/b82664e...2134d54.html" title="Last updated on Jan 4, 2018, 12:02 AM GMT (2134d54)">Diff</a>

Meta: use new WHATWG boilerplate and license

---

notifications.bs

***
<a href="https://whatpr.org/notifications/104.html" title="Last updated on Feb 27, 2018, 11:18 AM GMT (5a8fbde)">Preview</a> | <a href="https://whatpr.org/notifications/104/4a296ed...5a8fbde.html" title="Last updated on Feb 27, 2018, 11:18 AM GMT (5a8fbde)">Diff</a>

Meta: update broken link to HTML's "update the image data"

---

notifications.bs

This reverts f2e3cad125ca7c7204889c214b392e3312fc5f74 and 53ebcf25458f7581570a228cfa11ad7cb27ff4ea.
It also ensures notificationclose is dispatched when replacing a notification.
(There are many inaccuracies remaining regarding tasks that need to be fixed in a follow-up.)
Tests: https://github.com/w3c/web-platform-tests/pull/5188.
Fixes #100.
***
<a href="https://whatpr.org/notifications/122.html" title="Last updated on Feb 27, 2018, 1:21 PM GMT (eb1c7e3)">Preview</a> | <a href="https://whatpr.org/notifications/122/d6f27bd...eb1c7e3.html" title="Last updated on Feb 27, 2018, 1:21 PM GMT (eb1c7e3)">Diff</a>

Add show and close events back

---

notifications.bs

***
<a href="https://whatpr.org/notifications/123.html" title="Last updated on Feb 27, 2018, 3:12 PM GMT (e2c930a)">Preview</a> | <a href="https://whatpr.org/notifications/123/1961618...e2c930a.html" title="Last updated on Feb 27, 2018, 3:12 PM GMT (e2c930a)">Diff</a>

Editorial: adopt more Infra terminology

---

notifications.bs

There are no implementations for this property, and the native
notification centers of various platforms make it hard to support this
properly.
- Windows Action Center toasts have an <audio> element supports
built-in sounds, as well as sounds included in an application's
package, but not freeform path and/or URL support.
- NSUserNotification (Mac OS and iOS) have a `soundName` property that
will be resolved against files in various local system directories.
- Android strongly prefers usage of the RingtoneManager for sounds.
- Based on Chrome for Linux statistics, the majority of Chrome users (80%+)
report that sounds are not supported in the system's notification server.
Even though it could be supported on certain platforms, it's currently
underspecified: which codecs should be supported …

Remove support for sounds from notifications

---

notifications.bs

This gives a more consistent story for event dispatching. The former setup was especially buggy if native replacement is not supported.
This also reduces duplication (such as waiting for fetches).
And it queues a task for the show and close events.
***
<a href="https://whatpr.org/notifications/126.html" title="Last updated on Feb 28, 2018, 6:28 PM GMT (46a1553)">Preview</a> | <a href="https://whatpr.org/notifications/126/459bf35...46a1553.html" title="Last updated on Feb 28, 2018, 6:28 PM GMT (46a1553)">Diff</a>

Merge replacing and displaying into showing

---

notifications.bs

Use the relevant settings object instead.
Fixes #86.
(Note that this builds upon #167.)
***
<a href="https://whatpr.org/notifications/168.html" title="Last updated on Apr 26, 2021, 6:46 AM UTC (c7f1660)">Preview</a> | <a href="https://whatpr.org/notifications/168/a3e44ea...c7f1660.html" title="Last updated on Apr 26, 2021, 6:46 AM UTC (c7f1660)">Diff</a>

Get rid of entry settings object usage

---

review-drafts/2021-07.bs

The [July 2021 Review Draft](https://notifications.spec.whatwg.org/review-drafts/2021-07/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/notifications/170.html" title="Last updated on Jul 19, 2021, 12:06 PM UTC (f9f59ff)">Preview</a> | <a href="https://whatpr.org/notifications/170/0ed9d85...f9f59ff.html" title="Last updated on Jul 19, 2021, 12:06 PM UTC (f9f59ff)">Diff</a>

Review Draft Publication: July 2021

---

notifications.bs

Continuing the mess I made in #175.
Fixes #93
***
<a href="https://whatpr.org/notifications/176.html" title="Last updated on Nov 22, 2021, 7:57 PM UTC (4eff822)">Preview</a> | <a href="https://whatpr.org/notifications/176/df1b6db...4eff822.html" title="Last updated on Nov 22, 2021, 7:57 PM UTC (4eff822)">Diff</a>

Restrict Notifications to secure contexts.

---

notifications.bs

***
<a href="https://whatpr.org/notifications/188.html" title="Last updated on Jan 16, 2023, 7:45 AM UTC (945a9de)">Preview</a> | <a href="https://whatpr.org/notifications/188/ed277b3...945a9de.html" title="Last updated on Jan 16, 2023, 7:45 AM UTC (945a9de)">Diff</a>

Meta: remove HTML anchor

---

notifications.bs

According to https://dontcallmedom.github.io/webdex/e.html#epoch-relative%20timestamp%40%40hr-time%25%25dfn, this is the last use.
***
<a href="https://whatpr.org/notifications/192.html" title="Last updated on Mar 22, 2023, 8:58 AM UTC (3525a7d)">Preview</a> | <a href="https://whatpr.org/notifications/192/14602f0...3525a7d.html" title="Last updated on Mar 22, 2023, 8:58 AM UTC (3525a7d)">Diff</a>

Editorial: Remove a use of "epoch-relative timestamp", in favor of newer terminology.

---

notifications.bs

Closes #193 
* WebKit
* Chromium per https://github.com/whatwg/notifications/pull/194#issuecomment-1551191216
* https://github.com/WebKit/WebKit/pull/13912
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1446893
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1834005
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=256828
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/notifications/194.html" title="Last updated on May 19, 2023, 12:57 PM UTC (a6b4f0c)">Preview</a> | <a href="https://whatpr.org/notifications/194/8b4002d...a6b4f0c.html" title="Last updated on May 19, 2023, 12:57 PM UTC (a6b4f0c)">Diff</a>

Default silent to platform convention

---

notifications.bs

***
<a href="https://whatpr.org/notifications/206.html" title="Last updated on Apr 4, 2024, 2:47 PM UTC (428832a)">Preview</a> | <a href="https://whatpr.org/notifications/206/fab345b...428832a.html" title="Last updated on Apr 4, 2024, 2:47 PM UTC (428832a)">Diff</a>

Editorial: Add a missing comma

---

notifications.bs

This will make it easier to give them more associated concepts.
***
<a href="https://whatpr.org/notifications/212.html" title="Last updated on Jul 10, 2024, 12:20 PM UTC (77e7817)">Preview</a> | <a href="https://whatpr.org/notifications/212/96a2c28...77e7817.html" title="Last updated on Jul 10, 2024, 12:20 PM UTC (77e7817)">Diff</a>

Editorial: modernize the language around actions

---

notifications.bs

And reorder a couple of things so they are consistent across concepts and IDL.
***
<a href="https://whatpr.org/notifications/215.html" title="Last updated on Jul 17, 2024, 3:39 PM UTC (c2f3fd2)">Preview</a> | <a href="https://whatpr.org/notifications/215/0fd4b82...c2f3fd2.html" title="Last updated on Jul 17, 2024, 3:39 PM UTC (c2f3fd2)">Diff</a>

Editorially: generally refer to end user

---

notifications.bs

The single use no longer needs to report the exception itself.
Part of whatwg/webidl#1425.
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/whatwg-notifications/216.html" title="Last updated on Aug 2, 2024, 6:18 PM UTC (d83c188)">Preview</a> | <a href="https://whatpr.org/notifications/216/221c867...d83c188.html" title="Last updated on Aug 2, 2024, 6:18 PM UTC (d83c188)">Diff</a>

Editorial: Update use of WebIDL "invoke a callback function"

---

notifications.bs

This makes the following changes:
- Instead of making create a notification deal directly with a service worker registration, we leave that to the callers. We also make service worker registration always present on a notification as "can have" fields are confusing and buggy.
- Stop requiring an environment settings object for create a notification as that won't necessarily be around for Declarative Web Push.
- Sprinkle some <div algorithm> around to reduce variable errors and make variables easier to track in user agents with JavaScript enabled.
***
<a href="https://whatpr.org/notifications/217.html" title="Last updated on Aug 23, 2024, 8:20 AM UTC (71809d3)">Preview</a> | <a href="https://whatpr.org/notifications/217/bd0b2dc...71809d3.html" title="Last updated on Aug 23, 2024, 8:20 AM …

Editorial: prepare create a notification for Declarative Web Push

---

notifications.bs

Also sprinkle some more `<div algorithm>` around.
***
<a href="https://whatpr.org/notifications/218.html" title="Last updated on Aug 23, 2024, 9:32 AM UTC (267e518)">Preview</a> | <a href="https://whatpr.org/notifications/218/9a8242e...267e518.html" title="Last updated on Aug 23, 2024, 9:32 AM UTC (267e518)">Diff</a>

Mark persistent notifications as a tracking vector

---

notifications.bs

***
<a href="https://whatpr.org/notifications/219.html" title="Last updated on Aug 23, 2024, 9:58 AM UTC (268e5e2)">Preview</a> | <a href="https://whatpr.org/notifications/219/d5618b0...268e5e2.html" title="Last updated on Aug 23, 2024, 9:58 AM UTC (268e5e2)">Diff</a>

Editorial: improve notification member types

---

notifications.bs

These steps are needed by Declarative Web Push. Make these steps invoke "fetch steps" directly at the same time as no caller needs the distinction.
***
<a href="https://whatpr.org/notifications/220.html" title="Last updated on Aug 26, 2024, 12:11 PM UTC (def07b9)">Preview</a> | <a href="https://whatpr.org/notifications/220/37649c3...def07b9.html" title="Last updated on Aug 26, 2024, 12:11 PM UTC (def07b9)">Diff</a>

Editorial: export notification show steps

---

notifications.bs

9a8242eba3cb369f5a0f102d4acb3c011493fb19 made this a responsible of the caller, but with Declarative Web Push the caller is in a different specification.
***
<a href="https://whatpr.org/notifications/225.html" title="Last updated on Nov 6, 2024, 2:15 PM UTC (307ffa4)">Preview</a> | <a href="https://whatpr.org/notifications/225/7b0aee1...307ffa4.html" title="Last updated on Nov 6, 2024, 2:15 PM UTC (307ffa4)">Diff</a>

Meta: export notification's service worker registration

---

notifications.bs

This is needed for Declarative Web Push.
***
<a href="https://whatpr.org/notifications/226.html" title="Last updated on Nov 7, 2024, 2:50 PM UTC (ecf4faa)">Preview</a> | <a href="https://whatpr.org/notifications/226/c032675...ecf4faa.html" title="Last updated on Nov 7, 2024, 2:50 PM UTC (ecf4faa)">Diff</a>

Editorial: rename action to notification action and export it
